#!/bin/bash -e

### BEGIN INIT INFO
# Provides:          lodgeit
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: lodgeit
# Description:       lodgeit paste service
### END INIT INFO

case "$1" in
    start)
        su www-data -c '/usr/bin/nohup /usr/bin/python /srv/lodgeit/lodgeit/manage.py runserver > /dev/null 2>&1 &'
        ;;
    stop)
        for pid in `pgrep -f '/usr/bin/python /srv/lodgeit/lodgeit/manage.py runserver'`
        do
            kill $pid
        done
        ;;
    restart)
        stop
        start
        ;;
    status)
        pgrep -f '/usr/bin/python /srv/lodgeit/lodgeit/manage.py runserver' ; exit $?
        ;;
    *)
        echo "Usage: {start|stop|restart|status}"
        exit 1
        ;;
esac
