---
- file: path=/var/lib/software-factory/nodepool_config state=touch

- name: Check last applied Nodepool config checksum
  command: cat /var/lib/software-factory/nodepool_config
  register: localconfig

- name: Check new Nodepool config checksum
  shell: chdir=/root/config git log --oneline nodepool/ && md5sum /etc/nodepool/_nodepool.yaml
  register: upstreamconfig

- name: Update nodepool configuration
  command: chdir=/root/config {{ item }}
  when: localconfig.stdout != upstreamconfig.stdout
  with_items:
    - /usr/local/bin/sf-nodepool-conf-update.sh apply

- name: Write config repo checksum matching current configuration
  copy: content="{{ upstreamconfig.stdout }}" dest=/var/lib/software-factory/nodepool_config
  when: localconfig.stdout != upstreamconfig.stdout
