#scp -r puppet $1:.
#ssh $1 "cd puppet ; FACTER_REDMINE_DATABASE_ADAPTER=mysql FACTER_REDMINE_DATABASE_NAME=redmine FACTER_REDMINE_DATABASE_HOST=localhost FACTER_REDMINE_DATABASE_USERNAME=root FACTER_REDMINE_DATABASE_PASSWORD=root puppet apply --modulepath modules/ redmine_node.pp"

cd puppet ; FACTER_CANONICAL_WEBURL=198.154.188.164 FACTER_SSHD_LISTEN_ADDRESS=0.0.0.0 FACTER_HTTP_LISTEN_PORT=2023 FACTER_EMAIL_PRIVATE_KEY=test@local FACTER_MYSQL_ADDRESS=127.0.0.1 FACTER_GERRIT_MYSQL_DB=reviewdb FACTER_GERRIT_MYSQL_USERNAME=gerrit2 FACTER_MYSQL_POST=3306 FACTER_GERRIT_MYSQL_SECRET=secret puppet apply --modulepath modules/ gerrit_node.pp
