---
- file: path=/var/lib/software-factory/jenkins_config state=touch

- name: Check local config
  command: cat /var/lib/software-factory/jenkins_config
  register: localconfig

- name: Check upstream config
  command: chdir=/root/config git log --oneline jobs/
  register: upstreamconfig

- name: Update jenkins jobs
  when: localconfig.stdout != upstreamconfig.stdout
  command: chdir=/root/config {{ item }}
  with_items:
    - rm -Rf /var/lib/jenkins/.cache/jenkins_jobs
    - jenkins-jobs -l debug --ignore-cache update --delete-old jobs/

- name: Write config repo sha1 matching current configuration
  copy: content="{{ upstreamconfig.stdout }}" dest=/var/lib/software-factory/jenkins_config
  when: localconfig.stdout != upstreamconfig.stdout
