---

- name: Check if fqdn has been changed
  stat: path=/root/fqdn_changed
  register: fqdn_changed

# This isn't required after restoring a backup with a different fqdn, only if
# the fqdn is changed on the existing deployment
- name: Reset Gerrit SSH user keys
  when: fqdn_changed.stat.exists
  shell: "{{ item }}"
  with_items:
    - mysql gerrit < /root/gerrit-restore-user-keys.sql
    - systemctl restart gerrit

- name: Remove outdated /usr/share/httpd/.ssh/known_hosts
  file: path=/usr/share/httpd/.ssh/known_hosts state=absent
  when: fqdn_changed.stat.exists

- name: Update config repo with correct fqdn
  when: fqdn_changed.stat.exists
  command: chdir=/root/config {{ item }}
  # Error if change is already in git repo (added before backup)
  ignore_errors: yes
  with_items:
    - sed -i -e 's/host=.*/host={{ fqdn }}/g' .gitreview
    - sed -i -e 's#zuul-cloner http://.*/r#zuul-cloner http://{{ fqdn }}/r#g' jobs/_default_jobs.yaml
    - sed -i -e 's#ssh root@managesf..* /usr/local/bin/sf-config-update.sh#ssh root@managesf.{{ fqdn }} /usr/local/bin/sf-config-update.sh#g' jobs/_default_jobs.yaml
    - git add .gitreview jobs/_default_jobs.yaml
    - git commit -m "Update with new fqdn"
    - git push git+ssh://{{ fqdn }}:29418/config master

- name: Restart zuul service
  when: fqdn_changed.stat.exists
  service: name=zuul state=restarted

- name: Restart zuul-merger service
  when: fqdn_changed.stat.exists
  service: name=zuul-merger state=restarted

- name: Remove /root/fqdn_changed
  when: fqdn_changed.stat.exists
  file: path=/root/fqdn_changed state=absent
