---
- name: Check if policy config is already in config-repo
  stat: path=/root/config/policies
  register: configrepo_policies

- name: Check if policy config has job api entries
  when: configrepo_policies.stat.exists == true
  shell: grep -q managesf.job:get /root/config/policies/policy.yaml
  register: grep
  ignore_errors: yes

- name: Include sfconfig.yaml to get fqdn
  include_vars: /etc/software-factory/sfconfig.yaml

- name: Init policy configuration
  when: configrepo_policies.stat.exists == true and grep.rc == 1
  command: chdir=/root/config {{ item }}
  with_items:
    - git fetch --all
    - git reset --hard origin/master --
    - git clean -f -x -d
    # Create default rules
    - /usr/local/bin/hieraedit.py --yaml /root/config/policies/policy.yaml managesf.job:get rule:any
    - /usr/local/bin/hieraedit.py --yaml /root/config/policies/policy.yaml managesf.job:stop rule:admin_or_service
    - /usr/local/bin/hieraedit.py --yaml /root/config/policies/policy.yaml managesf.job:run rule:admin_or_service
    - git add policies
    - git commit -m "Initialize job API policies"
    - git push git+ssh://{{ fqdn }}/config master
